#!/usr/bin/env bash
# transfers a file from our client to a server

# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_path="$4"

# Construct the scp command with required parameters
scp -o StrictHostKeyChecking=no -i "$ssh_path" "$file_path" "$username@$server_ip":~/
