#!/usr/bin/env bash
#displays numbers from 1 to 20

hour=0
while [ "$hour" -lt 13 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ "$minutes" -lt 60 ]
    do
	echo "$minutes"
	(( minutes++ ))
    done

    (( hour++ ))
done
